### ISSUE TITLE
git submodule logic changes remotes

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#136]
I was wondering why the URLs of remotes of submodules where being changed until I realized the issue was with `make modules`.

To reproduce:

```sh
$ cd core
$ git remote add kba https://github.com/kba/ocrd-core
$ git checkout -t kba/logging-test
$ git remote -v
kba     https://github.com/kba/ocrd-core (fetch)
kba     https://github.com/kba/ocrd-core (push)
origin  https://github.com/OCR-D/core.git (fetch)
origin  https://github.com/OCR-D/core.git (push)
```

Now, if I run `make modules` and change back into `core`:

```sh
$ make modules OCRD_MODULES=core
sem --fg --id ocrd_all_git git submodule sync  core
Synchronizing submodule url for 'core'
if git submodule status  core | grep -qv '^ '; then \
        sem --fg --id ocrd_all_git git submodule update --init  core && \
        touch core; fi
Submodule path 'core': checked out '320a2fdeda6836bc4da522620bf169c22d471cbd'
$ cd core
$ git remote -v
kba     https://github.com/OCR-D/core.git (fetch)
kba     https://github.com/OCR-D/core.git (push)
origin  https://github.com/OCR-D/core.git (fetch)
origin  https://github.com/OCR-D/core.git (push)
```

I understand that the `submodule update` will change to the recorded submodule commit.

I **do not** understand how and why the remote URL is changed.

**Comment by bertsky** [comment]
> I **do not** understand how and why the remote URL is changed.

That's the doing of `git submodule sync`. Remember we had to introduce this because whenever we change submodule URLs or local paths upstream (which has already happened several times now), our users should get updated without extra effort (and back whenever they checkout an older version).

My guess is that because you had previously checked out from the other remote, `sync` now felt responsible for that remote. Probably could be considered a bug in git IMHO.

Maybe it would help to _first_ `git submodule update` and _then_ `git submodule sync` generally. (Which I guess would still be okay for first-time use because we already use `--init` as well.) What do you think?

**Comment by kba** [comment]
> Maybe it would help to _first_ `git submodule update` and _then_ `git submodule sync` generally. (Which I guess would still be okay for first-time use because we already use `--init` as well.) What do you think?

I can confirm that this fixes the issue, running `git submodule sync` after `git submodule update`. If there are no side-effects, that would be a good solution for me.

**Comment by bertsky** [comment]
> If there are no side-effects, that would be a good solution for me.

I'm not fully certain. Maybe it's necessary to do update-sync-update to be on the safe side. (Because if upstream changes a submodule URL _and_ commit hash, our makefile still needs to apply both.)

**Comment by kba** [comment]
Since this is likely an issue affecting only me, and I know about it and have workarounds, let's close this.

**Comment by stweil** [comment]
It's a me too issue.
