### ISSUE TITLE
Document `parallel --citation`

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_all#139]
Users should run `parallel --will-cite` or they will be flooded with spam about citing the paper that GNU parallel is based on.

**Comment by mnoelte** [comment]
Or they should run `parallel --citation` and type `will cite` when asked for!?

**Comment by bertsky** [comment]
IMO we should run that command (piping `will cite` to stdin) as part of the `custom-deps-ubuntu` recipe as an automatic workaround. Not sure about non-Debian/Ubuntu users though (so yes, documentation might be needed anyway).

Sorry about all that BTW. If I had considered that problem earlier, I would not have suggested using `parallel` for our deployment in the first place.

**Comment by kba** [comment]
I think the easiest solution is to touch `$HOME/.parallel/will-cite`.

**Comment by bertsky** [comment]
> I think the easiest solution is to touch `$HOME/.parallel/will-cite`.

But what if `parallel` changes this implementation detail?

The advantage of merely touching the config file is that we can use the same assumption to work around our `sudo` context in native installations, e.g. by `chown -R --reference=$(CURDIR) .parallel` (as in the existing recipe after recursive `deps-ubuntu`).

Other alleys could be using the sudo-defined environment variables `SUDO_UID` and `SUDO_GID` to switch back to the original user.

**Comment by bertsky** [comment]
> > I think the easiest solution is to touch `$HOME/.parallel/will-cite`.
> 
> But what if `parallel` changes this implementation detail?
> 
> The advantage of merely touching the config file is that we can use the same assumption to work around our `sudo` context in native installations, e.g. by `chown -R --reference=$(CURDIR) .parallel` (as in the existing recipe after recursive `deps-ubuntu`).

An additional problem here is that – depending on sudoers policy – `HOME` might or might not get set to the target user by `sudo`. Since we need `parallel` both in priviledged (`sudo make deps-ubuntu` submodules) and non-priviledged (`make all` submodules) context, we have to "register" it for both users. But we cannot even be sure where their HOME is (without knowing the sudoers policy).

So we have no choice but to use the functional approach, i.e. `echo will-cite | parallel --citation`. And since we _also_ cannot know for sure when `sudo` is used, let's just do this **every time** we want to use `parallel` or `sem` (in a canned recipe, like our `WGET` wrapper).

**Comment by kba** [comment]
> So we have no choice but to use the functional approach, i.e. `echo will-cite | parallel --citation`. And since we _also_ cannot know for sure when `sudo` is used, let's just do this **every time** we want to use `parallel` or `sem` (in a canned recipe, like our `WGET` wrapper).

If that's what it takes... Since this is only used for submodule management, it's a manageable (though ridiculous) overhead.

**Comment by bertsky** [comment]
> Sorry about all that BTW. If I had considered that problem earlier, I would not have suggested using `parallel` for our deployment in the first place.

I forgot to mention again `parallel` was also already required for workflow-configuration's GPU semaphore. So it was necessary to fix this anyway.

**Comment by kba** [comment]
> > Sorry about all that BTW. If I had considered that problem earlier, I would not have suggested using `parallel` for our deployment in the first place.
> 
> I forgot to mention again `parallel` was also already required for workflow-configuration's GPU semaphore. So it was necessary to fix this anyway.

Sure, no one's blaming anyone, we just need a solution. If workflow-configuration users profit from that particular nonsense being solved for them by ocrd_all, all the better.

**Comment by stweil** [comment]
That "functional approach" is not what was intended by the authors of GNU parallel. I think we should respect that and either live with the consequences (lots of messages or manual acceptance of the conditions) or use code without GNU parallel.

I am not really happy with the additional requirement to install GNU parallel and the way how it was introduced. Users of `ocrd_all` who had a working build environment are now confronted with an error message for the missing `sem` executable. There should at least be an error message which suggests to install GNU parallel.

**Comment by bertsky** [comment]
> That "functional approach" is not what was intended by the authors of GNU parallel.

It certainly was not. They even suggest you have to pay 10000 EUR before you are "entitled" to do that (in the man-page).
See https://savannah.gnu.org/bugs/?47076 etc.

> I think we should respect that and either live with the consequences (lots of messages or manual acceptance of the conditions) or use code without GNU parallel.

We cannot live with that message, because it actually **breaks** the behaviour of the software (sem never enters).

GNU parallel is under GPL and thus we have all the freedom to do that. In fact, I wonder why Debian/Ubuntu does not simply patch out this feature. It's disrespectful of users and undermines the GNU spirit.

> Users of `ocrd_all` who had a working build environment are now confronted with an error message for the missing `sem` executable. There should at least be an error message which suggests to install GNU parallel.

That requirement was practically already present, because `workflow-configuration` had it (which is enabled by default for native installation and in all Docker variants). It's also mentioned in the README (along dependencies like `git` and `make`). It also comes with `make deps-ubuntu`.

But you're right, we should additionally check for `sem` and fail with a good error message because it's not obvious that this belongs to GNU parallel.

**Comment by ole-tange** [comment]
I was alerted to your discussion.

The reason for the citation notice is covered here: http://git.savannah.gnu.org/cgit/parallel.git/tree/doc/citation-notice-faq.txt
I hope you at least will read the last 3 lines of the FAQ.

If `sem` never enters without first running `parallel --citation`, then it is a bug, and you should make an MCVE and file a bugreport (See https://www.gnu.org/software/parallel/man.html#REPORTING-BUGS).

**Comment by bertsky** [comment]
Hi @ole-tange and welcome to our discussion!

> The reason for the citation notice is covered here: http://git.savannah.gnu.org/cgit/parallel.git/tree/doc/citation-notice-faq.txt
> I hope you at least will read the last 3 lines of the FAQ.

As you can see above, we even studied the threads about this on your mailing list and issue tracker.
Also, @stweil already [alerted](https://github.com/OCR-D/ocrd_all/pull/155) us to your FAQ and the `--no-notice` workaround for scripts (which is not mentioned in the man-page, unfortunately).

All this has been going back and forth these days – I guess it's next to impossible to follow from the outside.

> If `sem` never enters without first running `parallel --citation`, then it is a bug

Yes, we have figured that by now, and no, we found no actual bug related to the notice. 

(The cause for our problem was always `~/.parallel` being owned by root instead of user due to `sudo` context, as well as stale `~/.parallel/semaphores` entries from previous failed attempts.)

We were [just discussing](https://github.com/OCR-D/ocrd_all/pull/153#issuecomment-675505817) again where to put your notice in our documentation...

**Comment by stweil** [comment]
@ole-tange, is [this citation](https://github.com/stweil/ocrd_all/tree/doc#acknowledgments) okay?

I added the reference also in the [German Wikipedia](https://de.wikipedia.org/wiki/GNU_parallel ).

**Comment by stweil** [comment]
@ole-tange, I just got the hint that the citation is ambiguous. You suggest to use _GNU Parallel 20200722 ('Privacy Shield')_, but Zenodo lists it as _GNU Parallel 20200622 ('Privacy Shield')_.

**Comment by ole-tange** [comment]
> @ole-tange, I just got the hint that the citation is ambiguous. You suggest to use _GNU Parallel 20200722 ('Privacy Shield')_, but Zenodo lists it as _GNU Parallel 20200622 ('Privacy Shield')_.

Yeah, I made a typo. I hoped no one would notice... naive me :) The version is 20200722.

**Comment by ole-tange** [comment]
> (The cause for our problem was always `~/.parallel` being owned by root instead of user due to `sudo` context, as well as stale `~/.parallel/semaphores` entries from previous failed attempts.)

But to me this is still a bug (not a serious one, but a bug nevertheless): You are confused why GNU Parallel does not behave correctly and you do not get any feedback that tells you what is wrong and what you can do to fix it. GNU Parallel strives to do better than that.

I have created https://savannah.gnu.org/bugs/index.php?58985 to track this issue.
