### ISSUE TITLE
docker: mixing preinstalled and user-downloaded resources

### ISSUE THREAD

**Issue by lena-hinrichsen** [OCR-D/ocrd_all#378]
In https://ocr-d.de/en/models we have this paragraph: 

> To download models to `./models` in the host FS and `/usr/local/share/ocrd-resources` in Docker:
> 
> ```sh
> docker run --user $(id -u) \
>   --volume $PWD/models:/usr/local/share/ocrd-resources \
> ocrd/all \
> ocrd resmgr download ocrd-tesserocr-recognize eng.traineddata\; \
> ocrd resmgr download ocrd-calamari-recognize default\; \
> ...
> ```
> 
> To run processors, as usual do:
> 
> ```sh
> docker run --user $(id -u) --workdir /data \
>   --volume $PWD/data:/data \
>   --volume $PWD/models:/usr/local/share/ocrd-resources \
>   ocrd/all ocrd-tesserocr-recognize -I IN -O OUT -P model eng
> ```
> 
> This principle applies to all `ocrd/*` Docker images, e.g. you can replace `ocrd/all` above with `ocrd/tesserocr` as well.

@kba came up with the question if that is still correct for `ocrd-tesserocr-*`: 
https://github.com/OCR-D/ocrd-website/pull/348/files/daf4fce2135f58b4f4ba43ef30e375e161e89651#r1159502451

**Comment by bertsky** [comment]
So our final idea was as follows:

> Symlink the `module` locations inside the docker container back to the `data` location mounted, i.e. `/usr/local/share/ocrd-resources`
> do this step **after** the models volume is already mounted, so the `mv` will effectively go from container to host storage – because in a `docker run --volume $PWD/models:/usr/local/share/ocrd-resources`, everything under `/usr/local/share/ocrd-resources` inside the container gets masked.
> define an `ENTRYPOINT` for this: a shell script that 
> - checks if /usr/local/share/ocrd-resources has been mounted
> - then iterates all the module directories:
>   ```
>   DATADIR=/usr/local/share/ocrd-resources/$EXECUTABLE
>   if [[ ! -d $DATADIR ]]; then
>     # make a persistent copy
>     cp -r $MODULEDIR $DATADIR
>   fi
>   # make sure downloaded models get persisted, too
>   ln -fs $DATADIR $MODULEDIR
>   ```
> - in the end, it [delegates to the `CMD`](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/nvidia_entrypoint.sh#L62-68)

**Comment by bertsky** [comment]
Alas, it does not work like this. Module directories frequently contain much more than just resource files (hence our file type filter in `ocrd_utils.list_all_resources`). More importantly, modules contain more than one processor – so the symlinking step (even with `--no-target-directory`) will clash. Also, the whole procedure is **slow** (even when using ocrd-all-tool.json), because each processor will have to be executed for `--dump-module-dir`.

**Comment by bertsky** [comment]
> > 1. Provide additional `--volume` options for every processor that uses `module` resources
> 
> No even that does not work, like I said above. If you mount a volume for these paths, then the preinstalled resources will become hidden (minimum default models from `install-tesseract` in ocrd_all/tesseract's case).

But if you use a **named volume**, then by default (unless using `nocopy` option), the container-internal files will in fact be copied to the host volume! 

I have tested this – it works beautifully:

    docker run -v tessdata:/usr/local/share/tessdata ocrd/all:maximum-cuda ocrd resmgr download ocrd-tesserocr-recognize frak2021.traineddata
    docker run -v tessdata:/usr/local/share/tessdata ocrd/all:maximum-cuda ocrd-tesserocr-recognize -P model frak2021 ...

So one gets persistence _and_ internal content. One can even interact with the filesystem on the host, it's just under a path which Docker chooses, in this case:

    docker volume inspect tessdata | jq '.[] | .Mountpoint'

(which yields `/data/docker/volumes/tessdata/_data`).

So all we need to do is:
1. add a `RUN` step in Dockerfile which iterates all processors and aggregates their `--dump-module-dir`, as described [here](https://github.com/OCR-D/core/issues/1059)
2. add a `RUN` step in Dockerfile which iterates all these module directories and moves them into `$XDG_DATA_HOME/ocrd-resources/EXECUTABLE` but then also symlinks in reverse direction

Change our documentation to use a named volume, e.g. `-v ocrd-models:/usr/local/share/ocrd-resources` instead of a bind-mount. (For /data, we can of course keep the bind-mount.)

(Care must be taken during 2 though to make sure that for each module, only one executable gets swapped like this, the others simply get symlinked from the first executable. Of course, if our ocrd-tool.json had specs on which executable needs which resources, it would be cleaner, but this should suffice.)

**Comment by bertsky** [comment]
> Thus, when running with `-v ocrd-models:/usr/local/share/ocrd-resources`, nothing further needs to be done.

Having implemented that in #380 and documented it in https://github.com/OCR-D/ocrd-website/pull/357, let's go one step further: Why not just symlink the internal `/usr/local/share/ocrd-resources` to the simpler `/models`, so users have less effort typing (and remembering) these calls?

**Comment by bertsky** [comment]
> let's go one step further: Why not just symlink the internal `/usr/local/share/ocrd-resources` to the simpler `/models`

done (in both PRs).
