### ISSUE TITLE
Broken build (ocrd_detectron2)

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_all#434]
See https://github.com/bertsky/ocrd_detectron2/issues/29 for details. It is broken with any Python version.

**Comment by bertsky** [comment]
Ah, now I get what's really going on. It's [still broken on master](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/1063/workflows/eb493901-4c2f-47ff-94b9-7fca5e688c7f/jobs/1463), but I could not reproduce elsewhere, because it's a bit fuzzy: it depends on whether kraken or detectron2 get installed first. If Kraken makes it, then due to its `torch~=2.1` requirement, we end up with https://github.com/pypa/setuptools/issues/4385.

**Comment by bertsky** [comment]
No, wait. That CI failure was from [your merge](https://github.com/OCR-D/ocrd_all/commit/c46cbcd67958e7222d02efde523702dc5df89e16). The current master with my #436 is [fine](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/1065/workflows/59e57e4a-1a23-4a44-9373-64dc9b5e9861).

And the reason this works is because I moved ocrd_kraken to the sub-venv, where it can install its own Pytorch independent of Detectron2.
